"""add site settings and hero slides

Revision ID: 0906a0e750b4
Revises: ac0e45a5a563
Create Date: 2026-08-20 14:31:37.894491

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0906a0e750b4'
down_revision: Union[str, None] = 'ac0e45a5a563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    # MySQL DDL is non-transactional; a prior failed run may have created hero_slides.
    if "hero_slides" not in tables:
        op.create_table(
            "hero_slides",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("image_url", sa.String(length=500), nullable=False),
            sa.Column("sort_order", sa.Integer(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            op.f("ix_hero_slides_id"), "hero_slides", ["id"], unique=False
        )
    if "site_settings" not in tables:
        op.create_table(
            "site_settings",
            sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
            sa.Column("hero_heading", sa.Text(), nullable=True),
            sa.Column("about_image_url", sa.String(length=500), nullable=True),
            sa.Column("about_heading", sa.String(length=255), nullable=True),
            sa.Column("about_body", sa.Text(), nullable=True),
            sa.Column("updated_at", sa.DateTime(), nullable=False),
            sa.CheckConstraint("id = 1", name="ck_site_settings_singleton"),
            sa.PrimaryKeyConstraint("id"),
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_settings')
    op.drop_index(op.f('ix_hero_slides_id'), table_name='hero_slides')
    op.drop_table('hero_slides')
    # ### end Alembic commands ###
