"""add image and display order to categories

Revision ID: 3f7bd62c27b6
Revises: d04f49c884b1
Create Date: 2026-08-15 21:22:35.283548

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '3f7bd62c27b6'
down_revision: Union[str, None] = 'd04f49c884b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column(
        'categories',
        sa.Column('display_order', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'display_order')
    op.drop_column('categories', 'image_url')
    # ### end Alembic commands ###
