"""add is_active to delivery groups

Revision ID: 642177c4fc15
Revises: 9c784f1d4fb7
Create Date: 2026-08-25 18:06:01.279647

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '642177c4fc15'
down_revision: Union[str, None] = '9c784f1d4fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Existing destinations stay live. server_default is required so MySQL can
    # add a NOT NULL column to tables that already have rows.
    op.add_column(
        "delivery_groups",
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_groups', 'is_active')
    # ### end Alembic commands ###
