"""add featured flags for products and subcategories

Revision ID: 814f331593d7
Revises: c31cb3935688
Create Date: 2026-08-16 11:45:28.343453

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '814f331593d7'
down_revision: Union[str, None] = 'c31cb3935688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Existing rows get False. server_default is required so MySQL can add
    # NOT NULL columns to tables that already have data.
    op.add_column(
        "categories",
        sa.Column("show_on_homepage", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "products",
        sa.Column("is_featured", sa.Boolean(), nullable=False, server_default=sa.false()),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_featured')
    op.drop_column('categories', 'show_on_homepage')
    # ### end Alembic commands ###
