"""add delivery prices and product weight

Revision ID: 9c784f1d4fb7
Revises: c8f21a9d4b70
Create Date: 2026-08-25 17:39:36.911663

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9c784f1d4fb7'
down_revision: Union[str, None] = 'c8f21a9d4b70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('handling_fee', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_groups_id'), 'delivery_groups', ['id'], unique=False)
    op.create_table('delivery_group_countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['delivery_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_name', name='uq_delivery_country_name')
    )
    op.create_index(op.f('ix_delivery_group_countries_group_id'), 'delivery_group_countries', ['group_id'], unique=False)
    op.create_index(op.f('ix_delivery_group_countries_id'), 'delivery_group_countries', ['id'], unique=False)
    op.create_table('delivery_weight_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('max_weight_kg', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['delivery_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_weight_tiers_group_id'), 'delivery_weight_tiers', ['group_id'], unique=False)
    op.create_index(op.f('ix_delivery_weight_tiers_id'), 'delivery_weight_tiers', ['id'], unique=False)
    op.add_column('orders', sa.Column('shipping_amount', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('products', sa.Column('weight_kg', sa.Numeric(precision=10, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'weight_kg')
    op.drop_column('orders', 'shipping_amount')
    op.drop_index(op.f('ix_delivery_weight_tiers_id'), table_name='delivery_weight_tiers')
    op.drop_index(op.f('ix_delivery_weight_tiers_group_id'), table_name='delivery_weight_tiers')
    op.drop_table('delivery_weight_tiers')
    op.drop_index(op.f('ix_delivery_group_countries_id'), table_name='delivery_group_countries')
    op.drop_index(op.f('ix_delivery_group_countries_group_id'), table_name='delivery_group_countries')
    op.drop_table('delivery_group_countries')
    op.drop_index(op.f('ix_delivery_groups_id'), table_name='delivery_groups')
    op.drop_table('delivery_groups')
    # ### end Alembic commands ###
