"""add customer accounts and sessions

Revision ID: e0d852c43a58
Revises: 0861b5f0497f
Create Date: 2026-08-16 14:38:00.794325

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e0d852c43a58'
down_revision: Union[str, None] = '0861b5f0497f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_sessions_customer_id'), 'customer_sessions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_sessions_id'), 'customer_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_customer_sessions_session_token'), 'customer_sessions', ['session_token'], unique=True)
    op.add_column('customers', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'hashed_password')
    op.drop_index(op.f('ix_customer_sessions_session_token'), table_name='customer_sessions')
    op.drop_index(op.f('ix_customer_sessions_id'), table_name='customer_sessions')
    op.drop_index(op.f('ix_customer_sessions_customer_id'), table_name='customer_sessions')
    op.drop_table('customer_sessions')
    # ### end Alembic commands ###
